language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-25.0.0
    - android-25
#    - platform-tools
#    - tools
#    - extra-android-support
    - extra-google-m2repository


#  licenses:
#    - android-sdk-license-.+
#    - google-gdk-license-.+

notifications:
  email: false

script: ./gradlew build check test
