language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.0
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew clean build check test

after_failure:
  script: cat /home/travis/build/Diolor/Swipecards/example/build/outputs/lint-results-debug.xml