language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-25.0.0
#    - platform-tools
#    - tools
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

script: ./gradlew clean build check test

after_failure: cat /home/travis/build/Diolor/Swipecards/example/build/outputs/lint-results-debug.xml