language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - extra-android-support

    - build-tools-25.0.0
    - android-25

  licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+

notifications:
  email: false

script: ./gradlew build check test
